name: Mr.Bruchez
favicon: null
layout_spectrum: 0.49961
typography_spectrum: 0.24771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060709'
    - '#fffffd'
    - '#7a6f6b'
    - '#b7b3b2'
    - '#fb9e01'
  brandStrength: 0.5035842
  lightness: 0.5053763
  saturation: 0.6810036
  rhythmicContrast: 0.6630824
purpose: []
